apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
  labels:
    app: my-flask-service
spec:
  selector:
    app: my-flask-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Use LoadBalancer for cloud K8s, NodePort/ClusterIP for local